### ISSUE TITLE
Disable warning messages

### ISSUE THREAD

**Issue by shaobo-he** [seahorn/sea-dsa#113]
Hello sea-dsa developers,

I'm seeing warning messages like `WARNING: inttoptr @ addr 0x27b7cc8 is (unsoundly) assumed to point to a fresh memory region.` printed out. I was wondering if it's possible to disable them since it's not very useful for non-developers.

**Comment by agurfinkel** [comment]
Sorry for taking so long to respond :(. If you submit a PR, I'll accept it. Better protect these messages by some `LOG` macro.
They are crucial for us because they indicate that the analysis is unsound. What was stopping me from acting on this is that we need to ensure that the messages still show up in our tools. But this has been taking too long. So if you submit a PR, I'll accept it and deal with my projects when I can.

**Comment by shaobo-he** [comment]
> Sorry for taking so long to respond :(. If you submit a PR, I'll accept it. Better protect these messages by some `LOG` macro.
> They are crucial for us because they indicate that the analysis is unsound. What was stopping me from acting on this is that we need to ensure that the messages still show up in our tools. But this has been taking too long. So if you submit a PR, I'll accept it and deal with my projects when I can.

No worries. I tried to use `LOG` to guard this error message in #115. Does it look reasonable to you? If so, I'll try to apply it to other similar warning messages in this file.
