### ISSUE TITLE
How to query DsaInfo for Context Sentitive information

### ISSUE THREAD

**Issue by pietroborrello** [seahorn/sea-dsa#127]
Hello,
what is the correct way to query context-sensitive information from `DsaInfo` in an llvm pass?
I'm currently querying `DsaInfo` through a wrapper similar to `seahorn::SeaDsa` in [SimpleMemoryCheck.cc](https://github.com/seahorn/seahorn/blob/bb7a7ef2c45e202772f1a89078db912eb1c32fc1/lib/Transforms/Instrumentation/SimpleMemoryCheck.cc#L189)

For each pointer `ptr` accessing memory in a function `F`, I call `DsaInfo::getDsaGraph(F)`, and then I obtain the corresponding Cell with `getCell(ptr)` from the graph, which gives me the `Node` and finally the `AllocSites`. 

However, I would like to be able to query pointer information of `ptr` in `F` with different contexts. But I didn't find a way to specify the caller of `F` under which I would like to retrieve pointer information.

### sample input
```c
int glob1 = 0;
int glob2 = 0;

__attribute_noinline__ int foo(int* ptr) {
    return *ptr + 1;
}

__attribute_noinline__ int func1(int* ptr) {
    return foo(ptr);
}

__attribute_noinline__ int func2(int* ptr) {
    return foo(ptr);
}

int main(int argc, char** argv) {
    return func1(&glob1) + func2(&glob2);
}
```

Here for example I would be able to differentiate that the memory access in `foo` points to `glob1` when called from `func1`, and to `glob2` when called from `func2`. 

However, compiling the example with `-O1 -flto -g` and analysing it in the custom pass (which either uses `BottomUpTopDownGlobalAnalysis` or `ContextSensitiveGlobalAnalysis`) printing the node that corresponds to `*ptr` in `foo` I get:
```
Node 0x...: flags=[tCSR] size=4 types={0:i32} links=[]  alloca sites=[@glob2 = internal global i32 0, align 4, !dbg !6,@glob1 = internal global i32 0, align 4, !dbg !0]
```
that contains both `glob1` and `glob2`, which I think is expected.

But if I try to get the Graph of `func1` or `func2` with `DsaInfo::getDsaGraph`, there is no cell that corresponds to the llvm value of `ptr`. So how should I specify the callsite information while querying pointer information?

### version
- sea-dsa: current dev10 branch
- llvm: 10

**Comment by caballa** [comment]
What I would do is to get the graphs of `func1` and `func2`, search for all callsites that call to `foo`, and then get the cell of the 1st argument at the callsite. This is what you tried and it didn't work?

Btw, and this is unrelated to how extract the information you want.  
`DsaInfo` is just a wrapper to `GlobalAnalysis`. `DsaInfo` computes some statistics about the dsa graphs that were useful for some of our checkers. Not sure if this true anymore. Make sure that you are always running the context-sensitive global analysis. If you are calling directly to `DsaInfo` you need to pass a flag to the `seadsa` binary (`--sea-dsa=cs` or `--sea-dsa=bu-td`) because `DsaInfo` is a LLVM pass. An alternative that gives you more control is to avoid running SeaDsa as a LLVM pass and create directly an instance of `ContextSensitiveGlobalAnalysis` or `BottomUpTopDownGlobalAnalysis`.

**Comment by pietroborrello** [comment]
Thank you for the fast reply.

> `DsaInfo` is just a wrapper to `GlobalAnalysis`. `DsaInfo` computes some statistics about the dsa graphs that were useful for some of our checkers. Not sure if this true anymore. Make sure that you are always running the context-sensitive global analysis. If you are calling directly to `DsaInfo` you need to pass a flag to the `seadsa` binary (`--sea-dsa=cs` or `--sea-dsa=bu-td`) because `DsaInfo` is an LLVM pass. An alternative that gives you more control is to avoid running SeaDsa as an LLVM pass and create directly an instance of `ContextSensitiveGlobalAnalysis` or `BottomUpTopDownGlobalAnalysis`.

I used `DsaInfo` just because I took inspiration from `SimpleMemoryCheck.cc` to deal with a new codebase, but I agree using `DsaAnalysis` or `BottomUpTopDownGlobalAnalysis` directly would be cleaner. Currently, I linked the sea-dsa static library to a new pass to which I forward the `--sea-dsa=butd-cs` flag that makes `DsaAnalysis` call `BottomUpTopDownGlobalAnalysis`.

> What I would do is to get the graphs of `func1` and `func2`, search for all callsites that call to `foo`, and then get the cell of the 1st argument at the callsite. This is what you tried and it didn't work?

I wanted to avoid querying the callsite arguments directly, since it would be less general, for example with something like:
```c
int foo(int* ptr) {
    return ptr[0x100] + 1;
}
```
Or any other operation involving `ptr`, would not be immediate to link the pointer used in the load to the function parameter.
I know I could visit the def-use chain in llvm backwards to understand on which parameter the pointer may depend, but is there something already built in sea-dsa to query points-to sets for pointers used in `foo`, depending on different calling contexts?
Especially to avoid manually dealing with value flow propagation, possibly through memory.

**Comment by agurfinkel** [comment]
SeaDsa itself does not natively provides such information. The reason is that it is summarizing analysis. It computes a summary of each function. In default mode, the top-down pass ensures that every call chain is taken into account. This, of course, significantly affects precision.

It is in principle possible to limit top-down propagation to a sequence of function calls, thus taking particular calling context into account. This is not difficult to do using existing code base, but it is not something SeaDsa provides out of the box.

**Comment by pietroborrello** [comment]
This make sense, thank you very much for the reply and for your great work
