### ISSUE TITLE
What is the status of LLVM 9 and LLVM 10 support?

### ISSUE THREAD

**Issue by zvonimir** [seahorn/sea-dsa#85]
We are looking to upgrade SMACK to LLVM 9 now, and also to LLVM 10 in a few months. I started working on it and updating SeaDSA along the way, but then @shaobo-he pointed out your `dev9` branch.

Is `dev9` branch where I can find stable support for LLVM 9?

More generally, what is your strategy in terms of LLMV updates?
For example, at this point your master branch is really outdated it seems. Any plans to merge e.g. `dev8` into master at some point?

Btw, we've been really happy with SeaDSA since we made the switch! So thanks again for developing it and for your help.

**Comment by agurfinkel** [comment]
`dev10` is the current development branch. We are not planning to actively support older versions. It should be easy to back port new changes from `dev10` to lower LLVM versions. 

`master` is always stale, as it is stable ;)

**Comment by caballa** [comment]
Yes, SeaDsa for llvm 10 should be usable

**Comment by zvonimir** [comment]
What about `dev9` branch? What is the status of that branch?
I understand that it does not have the latest and greatest features, but can we consider it to be stable/tested?

**Comment by agurfinkel** [comment]
I moved from `dev5` to `dev10`, making recovery points along the way in case I needed to go back. `dev9` is most stable since for a while we thought we will stick with `llvm9`. If it works, you should be able to use it. It should also be almost trivial to cherry-pick any fixes from `dev10` to `dev9`. We are happy to accept PRs and maintain older branches for clients.

**Comment by zvonimir** [comment]
Got it. Thanks for these clarifications. Let me see how LLVM 9 goes.
